[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='95741305186a8c4430f50dadc4fe6f1e5ea90f3c7832914cf7cc131b2dd80f39'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
